### ISSUE TITLE
Structure Javascript project

### ISSUE THREAD

**Issue by stonezzang** [stonezzang/js-project-env#3]
## Specification
Structure project with javascript

## Todos
- [x] Structure javascript project with [Yarn](https://yarnpkg.com/lang/en/)
- [x] Modify README.md
- [x] Configure testing environment
